### ISSUE TITLE
Build and installing app to Simulator or device.

### ISSUE THREAD

**Issue by nicklanasa** [swift-emacs/swift-mode#118]
Essentially, being able to run xcodebuild on a project to see if it fails and succeeds.

Also, the ability to install the app into the Simulator/Device of choice if the build does succeed. 

I actually have a script that does some of this and could implement it in lisp with some time.

Either way, would love to know what you guys think!

Thanks

**Comment by ap4y** [comment]
I think it will be helpful, setting up `xcodebuild` and something like `ios-sim` may take some time. My best idea is to hook it up with [compilation mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation-Mode.html#Compilation-Mode), wonder if someone has idea how to do it properly. In my projects previously I was writing `Makefile` and used it with `compilation-mode`.

**Comment by nicklanasa** [comment]
@ap4y Right how I have it building a workspace and inserting the output in another buffer. Although, `compilation-mode` seems much more useful. I'll take a look.

**Comment by taku0** [comment]
Building and installing to Simulator is implemented for #139. I have no idea how to install app to device from terminal.
