### ISSUE TITLE
For loop with `..<` has indentation problem

### ISSUE THREAD

**Issue by ccqpein** [swift-emacs/swift-mode#130]
~~~swift
for i in 1..<patternA.count {
                     //indentation here
                     for ii in 0..<i {
                                       //indentation here
~~~

I fix this issues with delete the `swift-mode.el` line 343 and line 289.

there are the command I deleted:

~~~elisp
289   ;((looking-at "<") (forward-char 1)
290    ;(if (looking-at "[[:upper:]]") "<T" "<"))
~~~

~~~elisp
343     ;((eq (char-before) ?<) (backward-char 1)
344      ;(if (looking-at "<[[:upper:]]") "<T" "<"))
~~~

I think I change the purpose which you suppose to. I submit this here maybe you can fix that in next version. 

Thank you!

**Comment by ccqpein** [comment]
I test again, only line 343 shall work. The change on line 289 is not necessary. 
I will give Pull request soon.

**Comment by taku0** [comment]
Fixed by the new indentation logic.
