### ISSUE TITLE
[discussion] move to organisation

### ISSUE THREAD

**Issue by chrisbarrett** [swift-emacs/swift-mode#133]
Any interest in me transferring this repository to an organisation? I have nearly no involvement, and think the active maintainers should be able to manage contributors.

@ap4y @bbatsov @uk-ar, and any other active contributors: chime in and let me know your thoughts.

**Comment by bbatsov** [comment]
Seems like the way to go. Let's create `swift-emacs` (similar to `clojure-emacs`) and move the package there.

**Comment by chrisbarrett** [comment]
Created https://github.com/swift-emacs

**Comment by chrisbarrett** [comment]
Before I hit transfer, the melpa recipe will need to be updated. Any other URLs floating around that will need changing?

**Comment by bbatsov** [comment]
> Before I hit transfer, the melpa recipe will need to be updated. Any other URLs floating around that will need changing?

Don't worry about this. Github will create redirects automatically.

**Comment by chrisbarrett** [comment]
Everyone gets admin powers!
