### ISSUE TITLE
[HELP-NEEDED] When set tab-width to 2, it is still not correctly indented with 2 space

### ISSUE THREAD

**Issue by shan199105** [swift-emacs/swift-mode#136]
I don't know if it is a emacs config problem, but I have set the tab width to 2

![image](https://cloud.githubusercontent.com/assets/2152195/19523438/8389885e-95e8-11e6-8370-073c5b7c4430.png)

Now when I write a function in swift

![image](https://cloud.githubusercontent.com/assets/2152195/19523493/b4f9e5dc-95e8-11e6-8733-7d6b34bdd47c.png)

It is still taking 4 space of indentation. 

I did research and seems that tab-width is everything we need to set to change indentation to 2 chars. 

Am I miss anything here? Please any help is appreciated. Thanks.

**Comment by alanshutko** [comment]
There's a key hint in the documentation above:
> NOTE: This controls the display width of a TAB character, and not
> the size of an indentation step.

You should instead set

````
swift-mode:basic-offset is a variable defined in ‘swift-mode-indent.el’.
Its value is 4

  This variable is safe as a file local variable if its value
  satisfies the predicate ‘integerp’.

Documentation:
Amount of indentation for block contents.

You can customize this variable.

[back]
````

**Comment by shan199105** [comment]
OH, it works. Thanks a lot.
