### ISSUE TITLE
Prompt looks garbled in Linux

### ISSUE THREAD

**Issue by samrat** [swift-emacs/swift-mode#137]
Running `run-swift`(passing arg "swift" instead of "xcrun swift"), I get a prompt that looks like this:

```
[1G[J 12>  [1G 12> [1G 12> [6G
```

**Comment by taku0** [comment]
Thank you for reporting. I'll investigate this on the weekends.

**Comment by taku0** [comment]
Fixed. See https://github.com/swift-emacs/swift-mode/issues/132#issuecomment-272624242.
