### ISSUE TITLE
Feature request: repl for project

### ISSUE THREAD

**Issue by Pitometsu** [swift-emacs/swift-mode#139]
see https://github.com/profburke/swiftreplmadness

**Comment by Pitometsu** [comment]
For iOS repl see http://stackoverflow.com/questions/26899664/how-can-i-use-swift-repl-with-ios-sdk/43478888#43478888

**Comment by taku0** [comment]
It seems that we need some separate commands for it.

For generic Swift package:

- Builds a shared library
- Runs REPL with appropriate options
    needs:
    - package name
- Utility command invoking them

For iOS app:

- Builds the project
    needs:
    - configuration
    - destination
- Launches the app in a simulator (optionally waiting for a deubbger)
    needs:
    - device name
    - whether or not to wait for a deubbger
- Attaches LLDB to the simulator
    needs:
    - path for `.app` file
    - application name

    Unfortunately, gud does not support LLDB, so we may need [RealGUD](https://github.com/realgud/realgud/wiki/Debuggers-Supported)
- Utility command invoking them

I cannot implement those commands soon, I will do it later.

**Comment by taku0** [comment]
Implemented:
- 186859017b1fed2b20ae5738d2b778c1a9b93c93
- 92f8eba4a46f57909d0612e6544bd9ad74113483

Only simple REPL for now. No fancy debugger functionalities.

**Comment by Pitometsu** [comment]
Not sure, would it work, but may be funny in `repl` https://github.com/johnno1962/injectionforxcode.

**Comment by Pitometsu** [comment]
There's https://github.com/realgud/realgud + https://github.com/realgud/realgud-lldb for fancy debugging.
