### ISSUE TITLE
Feature request: jump to declaration

### ISSUE THREAD

**Issue by Pitometsu** [swift-emacs/swift-mode#140]
Is it possible to achieve "jump to symbol declaration" in `swift-mode`?

**Comment by taku0** [comment]
We can use ctags:

1. Append [this ctags setting from swift.vim](https://github.com/keith/swift.vim/blob/master/ctags/swift.cnf) to `~/.ctags`.
2. Run `find . -name '*.swift' -print0 | xargs -0 ctags -e` in your project root directory.
    This will create an index file named `TAGS`.
    We need [Exuberant Ctags](http://ctags.sourceforge.net/) or [universal ctags](https://github.com/universal-ctags/ctags). `ctags` bundled with Emacs does not seems to work.
    If you get `Invalid character class name` error, replace `[[:<:]]` and `[[:>:]]` in the `.ctags` file with `\b`.
3. Type `M-.` in Swift code. Emacs may ask you where is `TAGS` file.

Alternatively, we may able to utilize [SourceKit](https://github.com/apple/swift/blob/master/tools/SourceKit/docs/Protocol.md), [SourceKitten](https://github.com/jpsim/SourceKitten), and/or [SourceKittenDaemon](https://github.com/terhechte/SourceKittenDaemon) to be smarter, but it will need a lot of work.

**Comment by Pitometsu** [comment]
Confirm: `universal ctags` works enough good. Many thans!
