### ISSUE TITLE
File header error

### ISSUE THREAD

**Issue by sunitjoshi** [swift-emacs/swift-mode#141]
I did a `package install-file swift-mode-pkg.el` and it gave me a "Package lacks a file header" error. I'm on Emacs 25.1.1.

**Comment by taku0** [comment]
Please execute `M-x package-install-file swift-mode-2.3.0.tar`. I will update the README.md. Thanks.

**Comment by sunitjoshi** [comment]
Thanks, this worked on emacs 25. On 24.5 I get an error "package.el is not yet initialized".

**Comment by sunitjoshi** [comment]
My bad, didn't have (package-initialize), in my .emacs.
It worked after I evaluated that statement.
