### ISSUE TITLE
No org-babel-execute for swift! in Org-mode swift code block

### ISSUE THREAD

**Issue by kandelvijaya** [swift-emacs/swift-mode#142]
Hi guys, 

I use org-mode for most of my note taking and journaling. I have bunch of swift code blocks and I wanted to execute them on the org file itself via C-c C-c with point inside the swift code block. 

And I see this message:
`no org-babel-execute function for swift!`

I would love to have such feature. I am fairly new to emacs and elisp so any pointers to implement this would be great.

**Comment by taku0** [comment]
I have little knowledge of `org-mode` or `org-babel`. I could not find a documentation about how to add a language.
However, `contrib/lisp/ob-*.el` in `https://code.orgmode.org/bzg/org-mode.git` may help you.
Grepping code also revails that `org-babel-execute-src-block` seeks a function named `org-babel-execute:swift`:

```emacs-lisp
      (let* ((lang (nth 0 info))
         ...
         (cmd (intern (concat "org-babel-execute:" lang)))
         ...)
        (unless (fboundp cmd)
          (error "No org-babel-execute function for %s!" lang))
```

**Comment by rudedogg** [comment]
Not sure, but https://github.com/zweifisch/ob-swift may work
