### ISSUE TITLE
Hi,Could you give me some suggestion of iOS SDK competetion?

### ISSUE THREAD

**Issue by oit63** [swift-emacs/swift-mode#143]
Hi, I am new to emacs, and I want to write code in emacs from moving from xcode and appcode.
And at first I have tried  generating yasnippet snippets with iOS SDK headers. but with this method, emacs becomes very slow. I know it is the best practice, but I can not find another one. Could you give some advice?

**Comment by taku0** [comment]
[company-sourcekit](https://github.com/nathankot/company-sourcekit) or [Swift Language Server](https://github.com/rlovelett/langserver-swift)+[lsp-mode](https://github.com/emacs-lsp/lsp-mode) may work, though I haven't tried them yet.

**Comment by Daopr** [comment]
thank you very much! company-sourcekit seems good, and I will try it tonight.

**Comment by msanders** [comment]
[emacs-ycmd](https://github.com/abingham/emacs-ycmd) is now an option as well (via [SwiftySwiftyVim](https://github.com/jerrymarino/swiftyswiftvim)).
