### ISSUE TITLE
[Question/Help] - How to configure indentation?

### ISSUE THREAD

**Issue by IcaroBritto** [swift-emacs/swift-mode#150]
Hi everyone.
I'm really new to the Emacs world and I just started using swift-mode.

I really don't know how to configure the indentation for a specific situation that I'm facing.
So the current behavior is this one:
```
func myFunction() {
    self.performBatchUpdates({
                                 // This is not what I want
                             }) {
        // ...
    }
}
```

And the behavior that I want is this one:
```
func myFunction() {
    self.performBatchUpdates({
        // This is what I want
    }) {
         // ...
    }
}
```

Can anyone help me with that?
Thank you!

**Comment by taku0** [comment]
`swift-mode` doesn't support that indentation.

When a method takes multiple functions, I recommend you to pass them with explicit labels:

```swift
func myFunction() {
  self.perform(
    batchUpdates: {
      // ...
    },
    completion: {
      // ...
    }
  )
}
```

Google also recommends so in [Google's swift style guide](https://google.github.io/swift/#trailing-closures).

**Comment by IcaroBritto** [comment]
Humm, I see.

Thank you for the replay, by the way :)
