### ISSUE TITLE
How to use running Docker swift container as REPL

### ISSUE THREAD

**Issue by stardiviner** [swift-emacs/swift-mode#155]
My Linux installed swift binary failed many times. So I give up. Until it is easy to install on my Arch Linux.
I use Swift Docker image to get a running Swift REPL. and other swift binaries.
But I don't know how to use running Docker swift container as swift REPL and binary path.

- for container Swift REPL, Emacs has an package `docker.el` can attach started container. so I can get an REPL buffer in Emacs. But if I want to make the REPL buffer work with swift-mode. I don't know how to set it up.
- for container binary path to be available for Emacs's swift-mode. I don't know how to do this.

**Comment by taku0** [comment]
It is intentional to distinguish multiple processes with different command line parameters like iOS app debugger and Swift module debugger processes. How about `*Swift [docker run --rm --privileged -it swift swift]*`?

**Comment by stardiviner** [comment]
> It is intentional to distinguish multiple processes with different command line parameters like iOS app debugger and Swift module debugger processes.

I see. Thanks

> How about *Swift [docker run --rm --privileged -it swift swift]*?

That's better. so that other Emacs packages like `ob-swift` can match it simpler. Thanks

**Comment by taku0** [comment]
Updated 348e1539775a118f82533b5c5999054ad6b79a1d
