### ISSUE TITLE
Hang interacting with which-func mode

### ISSUE THREAD

**Issue by dabrahams** [swift-emacs/swift-mode#157]
Open this file, turn on which-func mode, C-n to the last line, and hit return.  It will hang

```swift
protocol P { func f() }
extension P { func g() { f() } }
struct X<T> : P {
    func f() { print("unconstrained") }
}

struct X<T> : where T : BinaryInteger {
    func f() { print("constrained") }
}
```

The backtrace I get is:

[Backtrace.txt](https://github.com/swift-emacs/swift-mode/files/3015157/Backtrace.txt)

**Comment by taku0** [comment]
Sorry, I missed this issue for long. Fixed by 04c8a621e9844ef3f7d53c41b046f71aadb1a9d2.  Thank you for reporting the issue.
