### ISSUE TITLE
Mode periodically loses characters as I type

### ISSUE THREAD

**Issue by cubranic** [swift-emacs/swift-mode#158]
I'm using swift-mode with Spacemacs on Emacs 26.1 (just a straight package-install, not as a layer). As I type, there is something that the mode does that causes it to swallow characters. I can tell that some kind of background operation is in progress when that happens because whenever a character is dropped I also see "Quit" appear in the minibuffer.

I tried to dig a little deeper by setting the "Enter debugger on Quit" and "Enter debugger on error", but it was never entered. I understand that this may be hard to reproduce on another machine, so if you give me any instructions on how to debug this further, I'd be happy to try it.

**Comment by taku0** [comment]
I have started Spacemacs 26.1 with Docker in Linux, and used it for a few minutes, but it was not reproduced.

- What OS do you use?
- What's your `dotspacemacs-editing-style`?
- Is it reproduced with [`spacemacs-docker`](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bdistributions/spacemacs-docker)?
- Is `flycheck` enabled?
- Only in `swift-mode`?

If you use Linux, try [a quick test](https://gist.github.com/taku0/ed5da0512e1bc3d69103374a46bf544e).

1. Open a Spacemacs
2. Visit a new file
3. Run the script

Try it a few times with different filenames, then compare the results with `diff`.

**Comment by cubranic** [comment]
(I should have clarified that I'm on a Mac.)

I started my Spacemacs with no .spacemacs and started with a clean config. I don't see the bug any more, so I'm next going to identify the differences with my own .spacemacs and report back here.

**Comment by cubranic** [comment]
It looks like an existing package in my .emacs.d/elpa/ was causing this. When I started with the same config and clean package directory, the bug doesn't show. (I suspect `company`, but it's not worth checking at this point.)
