### ISSUE TITLE
I am not able to set the default indent to 2 spaces.

### ISSUE THREAD

**Issue by coyo8** [swift-emacs/swift-mode#160]
I updated my emacs configuration which has 2 spaces as default indentation and works for all other major mode but for swift-mode it doesn't work.

I guess it happens because of this line as we are setting the indent to 4 spaces and it overrides the default configuration.

```
defcustom swift-mode:basic-offset 4
  "Amount of indentation for block contents."
  :type 'integer
  :group 'swift
:safe 'integerp)
```
I am new to emacs and so I don't know elisp but if you can guide to how to add configurable indentation, I will work on it.

**Comment by taku0** [comment]
`M-x` `customize-group` → `swift` → `Swift Mode:Basic Offset`, or `M-x` `customize-option` → `swift-mode:basic-offset`.

**Comment by coyo8** [comment]
It fixed the issue. Thanks a lot @taku0 :)
