### ISSUE TITLE
How do you configure what scheme to build?

### ISSUE THREAD

**Issue by schloes** [swift-emacs/swift-mode#163]
I haven't been able to find any documentation on `build-ios-app` function. It defaults to a UITest scheme, rather than the one I need to build. Is there a way to configure this?

**Comment by taku0** [comment]
Try `M-x describe-function` then `swift-mode:build-ios-app` to find the documentation.

Use `C-u` prefix (`C-u M-x swift-mode:build-ios-app`) to supply arguments interactively.  Once you supply a scheme, it will be set as a default.

If you cannot choose a scheme even with `C-u` perfix, please paste the result of `xcodebuild -list -json` from a terminal.
