### ISSUE TITLE
Protocol indentation

### ISSUE THREAD

**Issue by kengruven** [swift-emacs/swift-mode#172]
Protocol members after `throws` are indented by swift-mode further than they should be:

```
protocol P {
    func f() throws
      func g()
    // comment
    func h() throws
      // comment
      var x: Int { get }
}
```

I think this should be indented more like:

```
protocol P {
    func f() throws
    func g()
    // comment
    func h() throws
    // comment
    var x: Int { get }
}
```

**Comment by taku0** [comment]
Fixed by https://github.com/swift-emacs/swift-mode/commit/2293e78c2c4660e6f3559411f649c4a34eb7e8d8. Thank you.

**Comment by kengruven** [comment]
Looks good here.  Thank you!
