### ISSUE TITLE
iMenu doesn't find declarations unless the opening brace of the containing top-level entity is on the same line

### ISSUE THREAD

**Issue by Mike-Woolley** [swift-emacs/swift-mode#173]
Consider this simple code fragment:

```swift
class Class1
{
	func fun1 () {}
	func fun2 () {}
}

class Class2
{
	func fun1 () {}
	func fun2 () {}
}
```

iMenu only shows the top-level entities:

![image](https://user-images.githubusercontent.com/44534958/135914804-d5a486e8-cff1-4ab2-a3ec-ad250487aba3.png)

However,  putting the { on the same line as the class names makes it work as expected:

```swift
class Class1 {
	func fun1 () {}
	func fun2 () {}
}

class Class2 {
	func fun1 () {}
	func fun2 () {}
}
```

![image](https://user-images.githubusercontent.com/44534958/135915124-6a3be682-23b3-4758-87b4-a17f053e4bb5.png)

It would be nice if this could be fixed, as Xcode copes with either version correctly 😄

![image](https://user-images.githubusercontent.com/44534958/135915826-6122eff6-4d7f-43b1-9798-253228b58a4d.png)

Thanks,
Mike

**Comment by taku0** [comment]
Fixed.
