### ISSUE TITLE
Function declarations get tagged with function-call-face

### ISSUE THREAD

**Issue by fermata101** [swift-emacs/swift-mode#174]
Function declarations should be getting tagged with the property swift-mode:function-name-face.  Instead, they are incorrectly tagged with swift-mode:function-call-face (as can be observed by doing M-x describe-text-properties with cursor on the function name.)

By default, both faces inherit from Emacs' default font-lock-function-name-face.  However, I prefer to highlight function declarations but not function calls.

I found that a simple fix was to swap the definitions of the two faces in swift-mode-font-lock.el, so that function-name-face comes before function-call-face.  This fixed it for me.

**Comment by taku0** [comment]
Fixed. Thank you for reporting.
