### ISSUE TITLE
How do I use the swift menu?

### ISSUE THREAD

**Issue by iT-Boyer** [swift-emacs/swift-mode#175]
When I execute `M-x swift-menu`:
```
command-execute: swift-menu must be bound to an event with parameters
```

**Comment by taku0** [comment]
It is intended to be a mouse event handler.
Use `F10`, <code>M-&#96;</code>, or `M-: (x-popup-menu t swift-menu)`

https://www.gnu.org/software/emacs/manual/html_node/emacs/Menu-Bar.html
