### ISSUE TITLE
comint-continue-subjob: Buffer *Swift REPL [xcrun swift]* has no process

### ISSUE THREAD

**Issue by iT-Boyer** [swift-emacs/swift-mode#183]
comint-continue-subjob: Buffer *Swift REPL [xcrun swift]* has no process

For example

1. new file `test.swift`
```swift
print("hello world")
```
2. run `send to buffer REPL`
3. log  in `*Swift REPL [xcrun swift]*` buffer
```
Welcome to Swift!

Subcommands:

  swift build      Build Swift packages
  swift package    Create and work on packages
  swift run        Run a program from a package
  swift test       Run package tests
  swift repl       Experiment with Swift code interactively

  Use `swift --help` for descriptions of available options and flags.

  Use `swift help <subcommand>` for more information about a subcommand.

Process xcrun swift finished
```

$ swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

**Comment by taku0** [comment]
Does this branch work? https://github.com/swift-emacs/swift-mode/tree/swift-repl-5.7
If it works, I will merge it to the `master`.

**Comment by iT-Boyer** [comment]
on Mac ，it's OK   When it's set to `swift repl`：
```elisp
(setq swift-mode:repl-executable "swift repl")
```
