### ISSUE TITLE
Syntax highlight error in function names that contain keywords

### ISSUE THREAD

**Issue by ksqsf** [swift-emacs/swift-mode#190]
See the screenshot:

<img width="347" alt="image" src="https://github.com/swift-emacs/swift-mode/assets/23358293/819757c8-2591-4bdf-a6df-c2c18daf0f56">

`focus_in` is a function name, but `in` is highlighted as a keyword.

**Comment by taku0** [comment]
Thank you for reporting this. Fixed: https://github.com/swift-emacs/swift-mode/commit/84059659de4da89d3d2902611cebed6d0423bf06
