### ISSUE TITLE
Indention with closure

### ISSUE THREAD

**Issue by roxlu** [swift-emacs/swift-mode#86]
Hey Chris, 

I merged your swift-mode this week and it's working a lot beter! Awesome work!

I'm only still having problems with idention. I've pasted some example code here:
https://gist.github.com/roxlu/3c899602069a7b471cae#file-newslocationviewcontroller-swift-L59-L60

Notice how the closure indention breaks. For some indention issues I found work-arounds but not
for this one.

Thanks

**Comment by roxlu** [comment]
Hey Chris, I just figured out why the indention isn't working. When I move this curly brace a bit up so it's directly positioned  after the close ) of the function the indention works again. I'm talking about this curly brace: https://gist.github.com/roxlu/3c899602069a7b471cae#file-newslocationviewcontroller-swift-L31

**Comment by ap4y** [comment]
Yeah, I'm pretty sure grammar for this case of declaration is currently missing, will check it at the weekend.

**Comment by chrisbarrett** [comment]
I'm gonna chime in here and thank you heaps Arthur for all your hard work, especially on the indentation! You basically own this package now. ;)

**Comment by ap4y** [comment]
Haha, thanks for the kind words Chris. That's may sound weird but `SMIE` can be fun once you get grasp of it :)

**Comment by taku0** [comment]
Closing in favor of the new indentation logic.
