### ISSUE TITLE
Swift 2 support

### ISSUE THREAD

**Issue by wiruzx** [swift-emacs/swift-mode#96]
- [ ] `guard`
- [ ] `do` blocks
- [ ] Error handling
  - [ ] `throws` in function declaration
  - [ ] `do catch` syntax
  - [ ] `try` keyword
- [ ] `defer`
- [ ] Pattern matching
  - [ ] `if` 
  - [ ] `for`
- [ ] `@testable`
- [ ] `repeat`
- [ ] new Extensions with predicates
- [ ] `indirect` cases in enums

**Comment by tharpa** [comment]
Please include support for the playground single line delimiter comment syntax `//:` [Playground Reference](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Playground_Ref/Chapters/MarkupReference.html) for the `M-x fill-paragraph` function.

**Comment by AlexChesters** [comment]
:+1:

**Comment by nicklanasa** [comment]
When will this mode have Swift 2 support?

**Comment by ap4y** [comment]
afaik no one started working on this issue, so it's hard to give any estimation when it will be implemented. As with any open source project, contributions are highly encouraged.

**Comment by taku0** [comment]
I have updated my personal branch to support Swift 2.1 https://github.com/taku0/swift-mode/tree/swift-2-indentation.

**Comment by taku0** [comment]
Swift 2.1 indentation demo: https://gist.github.com/taku0/8455a1c9f87b11550599

**Comment by taku0** [comment]
Swift 2.2 will introduce `associatedtype` keyword to replace `typealias` used for associated type declarations.
https://github.com/apple/swift-evolution/blob/master/proposals/0011-replace-typealias-associated.md

**Comment by taku0** [comment]
Closing in favor of the new indentation logic.
